# Generated by Django 4.0.5 on 2022-07-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=280, verbose_name='Post content')),
                ('published_at', models.DateTimeField(auto_now=True, verbose_name='publication date')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
                'ordering': ['-published_at'],
            },
        ),
    ]
