# Generated by Django 4.0.5 on 2022-07-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='related_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.tweets', verbose_name='Tweet'),
        ),
    ]
